### ISSUE TITLE
Cryptodome module not found error

### ISSUE THREAD

**Issue by Dandub** [fashberg/WThermostatBeca#39]
Hi,

I'm getting the above error while trying to flash my BHT-002 thermostat.
Please see below. 
Any help is much appreciated.

Thanks,
Dan

Starting smart config pairing procedure
Waiting for the device to install the intermediate firmware
Traceback (most recent call last):
  File "./smartconfig/main.py", line 15, in <module>
    from smartconfig import smartconfig
  File "/home/dan/tuya-convert/scripts/smartconfig/smartconfig.py", line 43, in <module>
    from multicast import multicast_head, encode_multicast_body
  File "/home/dan/tuya-convert/scripts/smartconfig/multicast.py", line 12, in <module>
    from Cryptodome.Cipher import AES
ModuleNotFoundError: No module named 'Cryptodome'

**Comment by fashberg** [comment]
Hi @Dandub 
Check https://github.com/ct-Open-Source/tuya-convert/issues/583
Kind Regards
Folke
